{
  parserClass="org.potniype4kin.textile.parser.TextileParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Textile"
  psiImplClassSuffix="Impl"
  psiPackage="org.potniype4kin.textile.psi"
  psiImplPackage="org.potniype4kin.textile.psi.impl"

  elementTypeHolderClass="org.potniype4kin.textile.psi.TextileType"
  elementTypeClass="org.potniype4kin.textile.psi.TextileElement"
  tokenTypeClass="org.potniype4kin.textile.psi.TextileToken"

  psiImplUtilClass="org.potniype4kin.textile.psi.impl.TextilePsiImplUtil"
}

textileFile ::= item*

private header ::= HEADER_START HEADER_TEXT EOL
private list ::= LIST_DELIM (LIST_TEXT EOL)+
private code ::= CODE_START+ CODE* CODE_END
private info ::= INFO_START+ INFO* INFO_END
private item ::= (header|list|code|info|TEXT|CHAPTER_BREAK|PARAGRAPH_BREAK)
